// Baza przepisów — każdy przepis to porcja na 2 osoby x 2 dni = 4 porcje.
// Wartości kaloryczne i makroskładniki są szacunkowe (na podstawie typowych wartości
// odżywczych surowych składników), oznaczone jako przybliżone w interfejsie.
// equipment: 'garnek' | 'thermomix' | 'blender' | 'frytkownica'
// categories składników: mieso | warzywa | nabial | zboza | przyprawy_sosy | inne

const RECIPES = [
  {
    id: 1,
    name: "Kurczak duszony w sosie pomidorowym z ryżem",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 715,
    protein: 56,
    carbs: 73,
    fat: 18,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Passata pomidorowa", amount: 400, unit: "g", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 3, unit: "ząbek", category: "warzywa" },
      { name: "Papryka czerwona", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Mix sałat", amount: 200, unit: "g", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 300, unit: "g", category: "warzywa" },
      { name: "Ogórek", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Ocet balsamiczny", amount: 2, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
      { name: "Bazylia suszona", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oregano suszone", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Sól", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
      { name: "Pieprz", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Pierś z kurczaka pokrój w kostkę, cebulę i czosnek pokrój drobno, paprykę w paski.",
      "W garnku rozgrzej oliwę, zeszklij cebulę z czosnkiem, dodaj kurczaka i podsmaż z każdej strony.",
      "Dodaj paprykę, passatę i przyprawy, duś pod przykryciem ok. 20 minut, aż kurczak będzie miękki.",
      "Ugotuj ryż w osobnym garnku wg instrukcji na opakowaniu.",
      "Pokrojony ogórek i pomidorki wymieszaj z mix sałat, oliwą i octem balsamicznym na lekką sałatkę.",
      "Rozłóż do 4 pudełek: ryż + sos z kurczakiem + sałatka (spakuj osobno, żeby nie zwiędła). Przechowuj w lodówce do 3-4 dni lub zamroź.",
    ],
  },
  {
    id: 2,
    name: "Pierś z kurczaka pieczona z warzywami korzeniowymi",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 628,
    protein: 55,
    carbs: 55,
    fat: 18,
    weight_g: 550,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 500, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 300, unit: "g", category: "warzywa" },
      { name: "Pietruszka korzeń", amount: 200, unit: "g", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Tymianek suszony", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Papryka słodka mielona", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Sól", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
      { name: "Pieprz", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Ziemniaki, marchew i pietruszkę obierz i pokrój w grube słupki.",
      "Warzywa wymieszaj z połową oliwy i przyprawami, włóż do frytkownicy na 15 minut w 190°C.",
      "Pierś z kurczaka natrzyj resztą oliwy i przyprawami, dodaj do koszyka frytkownicy.",
      "Piecz razem jeszcze 12-15 minut w 190°C, aż kurczak osiągnie 75°C wewnątrz.",
      "Podziel na 4 pudełka razem z warzywami.",
    ],
  },
  {
    id: 3,
    name: "Gulasz z indyka z kaszą gryczaną",
    protein_source: "Indyk",
    equipment: ["garnek"],
    portions: 4,
    kcal: 690,
    protein: 58,
    carbs: 63,
    fat: 19,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z indyka", amount: 600, unit: "g", category: "mieso" },
      { name: "Kasza gryczana", amount: 320, unit: "g", category: "zboza" },
      { name: "Cebula", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Koncentrat pomidorowy", amount: 3, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Bulion drobiowy", amount: 400, unit: "ml", category: "przyprawy_sosy" },
      { name: "Mix sałat", amount: 200, unit: "g", category: "warzywa" },
      { name: "Ogórek", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
      { name: "Ocet winny", amount: 1, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Papryka słodka mielona", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Kminek mielony", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Sól, pieprz", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Indyka pokrój w kostkę, cebulę i paprykę drobno.",
      "W garnku zeszklij cebulę na oliwie, dodaj indyka i obsmaż.",
      "Dodaj paprykę, koncentrat, przyprawy i bulion, duś pod przykryciem 25 minut.",
      "Ugotuj kaszę gryczaną wg instrukcji na opakowaniu.",
      "Pokrojonego ogórka wymieszaj z mix sałat, oliwą i octem na sałatkę.",
      "Rozłóż gulasz z kaszą i sałatką do 4 pudełek.",
    ],
  },
  {
    id: 4,
    name: "Chili z indykiem, fasolą i ryżem",
    protein_source: "Indyk",
    equipment: ["garnek"],
    portions: 4,
    kcal: 800,
    protein: 58,
    carbs: 88,
    fat: 19,
    weight_g: 750,
    ingredients: [
      { name: "Indyk mielony", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Fasola czerwona z puszki", amount: 240, unit: "g", category: "przyprawy_sosy" },
      { name: "Kukurydza z puszki", amount: 150, unit: "g", category: "przyprawy_sosy" },
      { name: "Passata pomidorowa", amount: 300, unit: "g", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Chili mielone / papryczka", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Kminek mielony", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Na oliwie zeszklij cebulę i czosnek, dodaj mięso mielone i obsmaż, rozdrabniając łyżką.",
      "Dodaj paprykę, passatę, odsączoną fasolę, kukurydzę i przyprawy, duś pod przykryciem 20 minut.",
      "Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż chili z ryżem do 4 pudełek, na wierzch dodaj garść mix sałat.",
    ],
  },
  {
    id: 5,
    name: "Kurczak curry kokosowe z ryżem",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 700,
    protein: 55,
    carbs: 70,
    fat: 21,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Mleko kokosowe light", amount: 400, unit: "ml", category: "nabial" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Fasolka szparagowa", amount: 250, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Curry przyprawa", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
      { name: "Sól", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, cebulę i czosnek drobno, paprykę i marchew w słupki.",
      "W garnku zeszklij cebulę z czosnkiem na oliwie, dodaj kurczaka i obsmaż.",
      "Dodaj paprykę, marchew, fasolkę szparagową, curry i mleko kokosowe, duś pod przykryciem 15-20 minut, aż warzywa zmiękną.",
      "Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż curry z ryżem do 4 pudełek.",
    ],
  },
  {
    id: 6,
    name: "Krem z kurczaka i warzyw",
    protein_source: "Kurczak",
    equipment: ["thermomix"],
    portions: 4,
    kcal: 604,
    protein: 54,
    carbs: 40,
    fat: 22,
    weight_g: 550,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 400, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Por", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Seler korzeń", amount: 100, unit: "g", category: "warzywa" },
      { name: "Śmietana 12%", amount: 120, unit: "g", category: "nabial" },
      { name: "Bulion drobiowy", amount: 400, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Sól, pieprz, gałka muszkatołowa", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Kurczaka ugotuj w bulionie do miękkości (ok. 20 minut), wyjmij i rozdrobnij lub pokrój w kostkę.",
      "Warzywa (ziemniaki, marchew, por, seler) umieść w naczyniu Thermomixa z bulionem, gotuj 20 minut/100°C.",
      "Zblenduj warzywa na gładki krem (stopniowo zwiększając obroty), dodaj śmietanę i przyprawy.",
      "Dodaj kawałki kurczaka do kremu, wymieszaj.",
      "Rozlej zupę-krem do 4 pojemników.",
    ],
  },
  {
    id: 7,
    name: "Kurczak teriyaki z ryżem i brokułem",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 718,
    protein: 56,
    carbs: 75,
    fat: 20,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Brokuł", amount: 400, unit: "g", category: "warzywa" },
      { name: "Sos sojowy", amount: 4, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Miód", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Imbir świeży", amount: 1, unit: "kawałek", category: "warzywa" },
      { name: "Olej sezamowy", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, czosnek i imbir zetrzyj/drobno posiekaj.",
      "Wymieszaj sos sojowy, miód, czosnek i imbir na sos teriyaki.",
      "W garnku podduś kurczaka na oleju sezamowym, zalej sosem i duś 10-12 minut, aż sos zgęstnieje.",
      "Ugotuj ryż i na parze/w wodzie ugotuj brokuł (różyczki) do miękkości.",
      "Rozłóż do 4 pudełek: ryż, brokuł, kurczak w sosie.",
    ],
  },
  {
    id: 8,
    name: "Gyros z piersi kurczaka z bulgurem i sosem czosnkowym",
    protein_source: "Kurczak",
    equipment: ["frytkownica", "blender"],
    portions: 4,
    kcal: 684,
    protein: 61,
    carbs: 60,
    fat: 20,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Bulgur", amount: 280, unit: "g", category: "zboza" },
      { name: "Jogurt naturalny 2%", amount: 400, unit: "g", category: "nabial" },
      { name: "Czosnek", amount: 3, unit: "ząbek", category: "warzywa" },
      { name: "Ogórek", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Pomidor", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Cebula czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Przyprawa gyros/oregano", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka natrzyj przyprawą gyros i oliwą, odstaw na 15 minut (lub dłużej w lodówce).",
      "Piecz w frytkownicy 15-18 minut w 190°C, aż będzie soczysty i przyrumieniony.",
      "W blenderze zmiksuj jogurt, czosnek, szczyptę soli i startego ogórka na sos czosnkowy.",
      "Ugotuj bulgur wg instrukcji na opakowaniu, pomidor i cebulę pokrój w kostkę.",
      "Rozłóż do 4 pudełek: bulgur, pokrojony kurczak, warzywa, sos osobno lub na wierzchu.",
    ],
  },
  {
    id: 9,
    name: "Kurczak w sosie musztardowo-miodowym z ziemniakami",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 676,
    protein: 56,
    carbs: 62,
    fat: 20,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Musztarda", amount: 3, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Miód", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Kapusta biała", amount: 300, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 100, unit: "g", category: "warzywa" },
      { name: "Jogurt naturalny 2%", amount: 100, unit: "g", category: "nabial" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wymieszaj musztardę z miodem i odrobiną oliwy, natrzyj kurczaka i odstaw na 10 minut.",
      "Ziemniaki pokrój w ćwiartki, wymieszaj z oliwą i solą.",
      "Piecz ziemniaki w frytkownicy 10 minut, dołóż kurczaka i piecz razem kolejne 15 minut w 190°C.",
      "Poszatkuj kapustę i marchew, wymieszaj z jogurtem na surówkę.",
      "Rozłóż do 4 pudełek: ziemniaki, kurczak, surówka.",
    ],
  },
  {
    id: 10,
    name: "Klopsiki z indyka w sosie pomidorowym z makaronem pełnoziarnistym",
    protein_source: "Indyk",
    equipment: ["garnek"],
    portions: 4,
    kcal: 745,
    protein: 58,
    carbs: 72,
    fat: 23,
    weight_g: 700,
    ingredients: [
      { name: "Indyk mielony", amount: 600, unit: "g", category: "mieso" },
      { name: "Makaron pełnoziarnisty", amount: 320, unit: "g", category: "zboza" },
      { name: "Bułka tarta", amount: 3, unit: "łyżka", category: "zboza" },
      { name: "Jajko", amount: 1, unit: "szt", category: "nabial" },
      { name: "Passata pomidorowa", amount: 500, unit: "g", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Ogórek", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Bazylia suszona", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wymieszaj mielonego indyka z jajkiem, bułką tartą, solą i pieprzem, uformuj klopsiki.",
      "W garnku obsmaż klopsiki na oliwie z każdej strony.",
      "Dodaj podsmażoną cebulę z czosnkiem, passatę i bazylię, duś pod przykryciem 20 minut.",
      "Ugotuj makaron pełnoziarnisty wg instrukcji na opakowaniu.",
      "Pokrojonego ogórka wymieszaj z mix sałat i odrobiną oliwy na sałatkę.",
      "Rozłóż do 4 pudełek: makaron, klopsiki w sosie, sałatka.",
    ],
  },
  {
    id: 11,
    name: "Chudy schab pieczony z ziemniakami i surówką z kapusty",
    protein_source: "Schab",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 649,
    protein: 55,
    carbs: 60,
    fat: 18,
    weight_g: 600,
    ingredients: [
      { name: "Schab wieprzowy chudy", amount: 700, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Kapusta biała", amount: 400, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 100, unit: "g", category: "warzywa" },
      { name: "Jogurt naturalny 2%", amount: 100, unit: "g", category: "nabial" },
      { name: "Majeranek suszony", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Schab natrzyj czosnkiem, majerankiem, solą i pieprzem, odstaw na 10 minut.",
      "Ziemniaki pokrój w ćwiartki, wymieszaj z oliwą i solą.",
      "Piecz schab i ziemniaki w frytkownicy 20-25 minut w 190°C (schab do temp. wewn. 70°C).",
      "Poszatkuj kapustę i marchew, wymieszaj z jogurtem na surówkę.",
      "Schab pokrój w plastry, rozłóż do 4 pudełek z ziemniakami i surówką.",
    ],
  },
  {
    id: 12,
    name: "Schab duszony w sosie chrzanowym z kaszą jęczmienną",
    protein_source: "Schab",
    equipment: ["garnek"],
    portions: 4,
    kcal: 624,
    protein: 59,
    carbs: 60,
    fat: 16,
    weight_g: 550,
    ingredients: [
      { name: "Schab wieprzowy chudy", amount: 700, unit: "g", category: "mieso" },
      { name: "Kasza jęczmienna", amount: 320, unit: "g", category: "zboza" },
      { name: "Chrzan tarty", amount: 3, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Śmietana 12%", amount: 150, unit: "g", category: "nabial" },
      { name: "Bulion drobiowy/warzywny", amount: 300, unit: "ml", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Marchew", amount: 100, unit: "g", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Schab pokrój w plastry, obsmaż w garnku na oliwie z obu stron.",
      "Dodaj pokrojoną cebulę i marchew, podlej bulionem, duś pod przykryciem 25 minut.",
      "Dodaj chrzan i śmietanę, wymieszaj i podgrzej (nie gotuj na dużym ogniu).",
      "Ugotuj kaszę jęczmienną wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: kasza, schab w sosie chrzanowym.",
    ],
  },
  {
    id: 13,
    name: "Wołowina duszona z warzywami i ryżem",
    protein_source: "Wołowina",
    equipment: ["garnek"],
    portions: 4,
    kcal: 711,
    protein: 45,
    carbs: 70,
    fat: 22,
    weight_g: 600,
    ingredients: [
      { name: "Wołowina chuda (udziec/łata)", amount: 700, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Marchew", amount: 200, unit: "g", category: "warzywa" },
      { name: "Pietruszka korzeń", amount: 100, unit: "g", category: "warzywa" },
      { name: "Cebula", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Koncentrat pomidorowy", amount: 2, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Bulion wołowy/warzywny", amount: 400, unit: "ml", category: "przyprawy_sosy" },
      { name: "Liść laurowy, ziele angielskie", amount: 2, unit: "szt", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wołowinę pokrój w kostkę, obsmaż w garnku na oliwie ze wszystkich stron.",
      "Dodaj cebulę, marchew i pietruszkę, chwilę podsmaż.",
      "Dodaj koncentrat, bulion i przyprawy, duś pod przykryciem 60-70 minut, aż mięso będzie miękkie.",
      "Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, wołowina duszona z warzywami.",
    ],
  },
  {
    id: 14,
    name: "Kurczak duszony po chińsku z ryżem",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 713,
    protein: 56,
    carbs: 78,
    fat: 20,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Fasolka szparagowa", amount: 200, unit: "g", category: "warzywa" },
      { name: "Sos sojowy", amount: 4, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Imbir świeży", amount: 1, unit: "kawałek", category: "warzywa" },
      { name: "Olej sezamowy", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka i warzywa pokrój w cienkie paski/słupki.",
      "W garnku rozgrzej olej sezamowy, obsmaż czosnek i imbir, dodaj kurczaka i obsmaż.",
      "Dodaj warzywa i sos sojowy, duś 8-10 minut na średnim ogniu, aż warzywa zmiękną.",
      "Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, kurczak z warzywami.",
    ],
  },
  {
    id: 15,
    name: "Roladki z kurczaka ze szpinakiem i serem light",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 681,
    protein: 65,
    carbs: 55,
    fat: 20,
    weight_g: 550,
    ingredients: [
      { name: "Pierś z kurczaka (cienkie płaty)", amount: 600, unit: "g", category: "mieso" },
      { name: "Szpinak świeży", amount: 200, unit: "g", category: "warzywa" },
      { name: "Ser light (typu mozzarella light)", amount: 160, unit: "g", category: "nabial" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Sól, pieprz, papryka słodka", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Rozbij płaty kurczaka, przypraw, na każdym ułóż szpinak i ser, zwiń w roladki (spinając wykałaczką).",
      "Ziemniaki pokrój w ćwiartki, wymieszaj z oliwą i solą.",
      "Roladki i ziemniaki włóż do frytkownicy, piecz 18-20 minut w 190°C.",
      "Sprawdź, czy kurczak jest dobrze wypieczony (min. 75°C wewnątrz).",
      "Rozłóż do 4 pudełek: roladki, ziemniaki.",
    ],
  },
  {
    id: 16,
    name: "Fajitas z kurczaka w tortilli pełnoziarnistej",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 730,
    protein: 63,
    carbs: 68,
    fat: 21,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Tortilla pełnoziarnista", amount: 8, unit: "szt", category: "zboza" },
      { name: "Papryka czerwona", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Fasola czarna z puszki", amount: 200, unit: "g", category: "przyprawy_sosy" },
      { name: "Sałata lodowa / mix sałat", amount: 250, unit: "g", category: "warzywa" },
      { name: "Pomidor", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Ser light starty", amount: 100, unit: "g", category: "nabial" },
      { name: "Jogurt naturalny 2% / salsa", amount: 150, unit: "g", category: "nabial" },
      { name: "Przyprawa do fajitas", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka pokrój w paski, wymieszaj z przyprawą do fajitas i oliwą.",
      "Paprykę i cebulę pokrój w paski.",
      "Piecz kurczaka i warzywa w frytkownicy 12-15 minut w 190°C, mieszając w połowie.",
      "Podgrzej tortille, dodaj fasolę i ser. Pomidora pokrój w kostkę.",
      "Rozłóż składniki do 4 pudełek osobno (kurczak z warzywami, tortille, fasola/ser, spora garść sałaty i pomidor, dodatki) — zawijaj z dużą ilością sałaty tuż przed jedzeniem, żeby były pełne i chrupiące.",
    ],
  },
  {
    id: 17,
    name: "Curry z indyka kokosowe z ryżem",
    protein_source: "Indyk",
    equipment: ["thermomix", "garnek"],
    portions: 4,
    kcal: 685,
    protein: 55,
    carbs: 70,
    fat: 19,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z indyka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Mleko kokosowe light", amount: 400, unit: "ml", category: "nabial" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Fasolka szparagowa", amount: 250, unit: "g", category: "warzywa" },
      { name: "Szpinak świeży", amount: 100, unit: "g", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Imbir świeży", amount: 1, unit: "kawałek", category: "warzywa" },
      { name: "Curry przyprawa", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "W naczyniu Thermomixa zmiksuj cebulę, czosnek i imbir na pastę (kilka sekund).",
      "Podsmaż pastę z curry (varoma/manual, kilka minut), dodaj pokrojonego indyka i paprykę.",
      "Dodaj mleko kokosowe i fasolkę szparagową, gotuj 15-20 minut w niskiej temperaturze, mieszając.",
      "Pod koniec gotowania wmieszaj szpinak, niech zwiędnie.",
      "Ugotuj ryż w garnku wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, curry z indyka.",
    ],
  },
  {
    id: 18,
    name: "Zapiekanka ryżowa z kurczakiem i brokułami",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 640,
    protein: 63,
    carbs: 60,
    fat: 18,
    weight_g: 550,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały (ugotowany wcześniej)", amount: 320, unit: "g", category: "zboza" },
      { name: "Brokuł", amount: 320, unit: "g", category: "warzywa" },
      { name: "Ser light starty", amount: 120, unit: "g", category: "nabial" },
      { name: "Jogurt naturalny 2%", amount: 150, unit: "g", category: "nabial" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Sól, pieprz, papryka słodka", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, podduś w garnku lub upiecz krótko wcześniej.",
      "Ugotowany ryż wymieszaj z kurczakiem, blanszowanym brokułem, czosnkiem i jogurtem.",
      "Przełóż do naczynia pasującego do frytkownicy, posyp serem.",
      "Piecz w frytkownicy 12-15 minut w 180°C, aż ser się zrumieni.",
      "Rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 19,
    name: "Kotlety mielone z piersi kurczaka z kuskusem",
    protein_source: "Kurczak",
    equipment: ["frytkownica", "thermomix"],
    portions: 4,
    kcal: 668,
    protein: 58,
    carbs: 60,
    fat: 20,
    weight_g: 550,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Kuskus", amount: 280, unit: "g", category: "zboza" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Jajko", amount: 1, unit: "szt", category: "nabial" },
      { name: "Bułka tarta", amount: 3, unit: "łyżka", category: "zboza" },
      { name: "Marchew", amount: 100, unit: "g", category: "warzywa" },
      { name: "Jabłko", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Jogurt naturalny 2%", amount: 100, unit: "g", category: "nabial" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Zmiel pierś z kurczaka (Thermomix, kilka sekund na obrotach pulsacyjnych) z cebulą.",
      "Dodaj jajko, bułkę tartą, sól i pieprz, wymieszaj, uformuj kotlety.",
      "Piecz kotlety w frytkownicy 12-15 minut w 190°C, obracając w połowie.",
      "Zalej kuskus wrzątkiem wg instrukcji, marchew i jabłko zetrzyj, wymieszaj z jogurtem na surówkę.",
      "Rozłóż do 4 pudełek: kuskus, kotlety, surówka.",
    ],
  },
  {
    id: 20,
    name: "Gulasz węgierski z chudej wołowiny z kaszą jęczmienną",
    protein_source: "Wołowina",
    equipment: ["garnek"],
    portions: 4,
    kcal: 715,
    protein: 49,
    carbs: 70,
    fat: 21,
    weight_g: 700,
    ingredients: [
      { name: "Wołowina chuda (udziec/łata)", amount: 700, unit: "g", category: "mieso" },
      { name: "Kasza jęczmienna", amount: 320, unit: "g", category: "zboza" },
      { name: "Cebula", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Koncentrat pomidorowy", amount: 2, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Papryka słodka mielona (do gulaszu)", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Bulion wołowy/warzywny", amount: 400, unit: "ml", category: "przyprawy_sosy" },
      { name: "Ogórek kiszony", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wołowinę pokrój w kostkę, obsmaż w garnku na oliwie.",
      "Dodaj cebulę i paprykę, chwilę podsmaż, dodaj paprykę słodką i koncentrat.",
      "Zalej bulionem, duś pod przykryciem 60-70 minut, aż mięso zmięknie.",
      "Ugotuj kaszę jęczmienną wg instrukcji na opakowaniu.",
      "Ogórek kiszony pokrój w plastry, podaj z mix sałat jako świeży dodatek.",
      "Rozłóż do 4 pudełek: kasza, gulasz, ogórek i sałata.",
    ],
  },
  {
    id: 21,
    name: "Kurczak w lekkim sosie serowym z brokułem i ziemniakami",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 600,
    protein: 64,
    carbs: 50,
    fat: 18,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Brokuł", amount: 300, unit: "g", category: "warzywa" },
      { name: "Ser light (topiony lub żółty)", amount: 160, unit: "g", category: "nabial" },
      { name: "Mleko 1,5%", amount: 200, unit: "ml", category: "nabial" },
      { name: "Czosnek", amount: 1, unit: "ząbek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, podduś w garnku na oliwie do miękkości.",
      "W drugim garnku podgrzej mleko z czosnkiem, dodaj starty ser i mieszaj do rozpuszczenia (sos serowy).",
      "Ugotuj ziemniaki i brokuł na parze/w wodzie.",
      "Połącz kurczaka z sosem serowym.",
      "Rozłóż do 4 pudełek: ziemniaki, brokuł, kurczak w sosie.",
    ],
  },
  {
    id: 22,
    name: "Pieczeń z piersi indyka z warzywami korzeniowymi",
    protein_source: "Indyk",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 600,
    protein: 52,
    carbs: 55,
    fat: 16,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z indyka (w całości)", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 600, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 250, unit: "g", category: "warzywa" },
      { name: "Pietruszka korzeń", amount: 150, unit: "g", category: "warzywa" },
      { name: "Czosnek", amount: 3, unit: "ząbek", category: "warzywa" },
      { name: "Musztarda", amount: 2, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Tymianek, rozmaryn", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
    ],
    steps: [
      "Pierś z indyka natrzyj musztardą, czosnkiem, ziołami, solą i pieprzem.",
      "Ziemniaki, marchew i pietruszkę pokrój w słupki, wymieszaj z oliwą i solą.",
      "Włóż warzywa do frytkownicy na 10 minut w 190°C, następnie dołóż indyka.",
      "Piecz razem 20-25 minut, aż indyk osiągnie 75°C wewnątrz.",
      "Pokrój indyka w plastry, rozłóż do 4 pudełek z warzywami.",
    ],
  },
  {
    id: 23,
    name: "Kurczak słodko-kwaśny z ryżem",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 705,
    protein: 57,
    carbs: 82,
    fat: 17,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Ananas w puszce (kawałki)", amount: 200, unit: "g", category: "przyprawy_sosy" },
      { name: "Papryka czerwona", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Brokuł", amount: 300, unit: "g", category: "warzywa" },
      { name: "Keczup", amount: 3, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Ocet ryżowy/winny", amount: 1, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Miód", amount: 1, unit: "łyżka", category: "inne" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, paprykę i cebulę w paski, brokuł w różyczki.",
      "W garnku obsmaż kurczaka na oliwie, dodaj cebulę, paprykę i brokuł.",
      "Wymieszaj keczup, ocet, miód i sok z ananasa, wlej do garnka razem z kawałkami ananasa.",
      "Duś 10-12 minut, aż sos zgęstnieje i brokuł zmięknie. Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, kurczak słodko-kwaśny z brokułem.",
    ],
  },
  {
    id: 24,
    name: "Krem z dyni z kurczakiem",
    protein_source: "Kurczak",
    equipment: ["thermomix"],
    portions: 4,
    kcal: 612,
    protein: 55,
    carbs: 45,
    fat: 22,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Dynia (miąższ)", amount: 600, unit: "g", category: "warzywa" },
      { name: "Ziemniaki", amount: 200, unit: "g", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Śmietana 12%", amount: 120, unit: "g", category: "nabial" },
      { name: "Bulion warzywny", amount: 400, unit: "ml", category: "przyprawy_sosy" },
      { name: "Pieczywo pełnoziarniste (na grzanki)", amount: 100, unit: "g", category: "zboza" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Imbir, gałka muszkatołowa", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Kurczaka ugotuj w bulionie do miękkości, wyjmij i rozdrobnij.",
      "Dynię, ziemniaki i cebulę umieść w naczyniu Thermomixa z resztą bulionu, gotuj 20 minut/100°C.",
      "Zblenduj na gładki krem, dodaj śmietanę i przyprawy.",
      "Pieczywo pokrój w kostkę i podpiecz na grzanki (frytkownica lub piekarnik, 5 minut).",
      "Rozlej krem do 4 pojemników, dodaj kurczaka i grzanki tuż przed jedzeniem.",
    ],
  },
  {
    id: 25,
    name: "Szaszłyki z kurczaka z kaszą gryczaną i sosem jogurtowym",
    protein_source: "Kurczak",
    equipment: ["frytkownica", "blender"],
    portions: 4,
    kcal: 641,
    protein: 63,
    carbs: 55,
    fat: 18,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Kasza gryczana", amount: 320, unit: "g", category: "zboza" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Cebula czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Jogurt naturalny 2%", amount: 200, unit: "g", category: "nabial" },
      { name: "Koperek świeży", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Czosnek", amount: 1, unit: "ząbek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka, paprykę, cukinię i cebulę pokrój w kawałki, nawlecz na patyczki (namoczone w wodzie).",
      "Skrop oliwą i przyprawami, piecz w frytkownicy 15 minut w 190°C, obracając w połowie.",
      "W blenderze zmiksuj jogurt, koperek, czosnek i szczyptę soli na sos.",
      "Ugotuj kaszę gryczaną wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: kasza, szaszłyki, sos osobno.",
    ],
  },
  {
    id: 26,
    name: "Chudy schab a'la pieczeń rzymska ze szpinakiem i jajkiem",
    protein_source: "Schab",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 654,
    protein: 61,
    carbs: 55,
    fat: 20,
    weight_g: 600,
    ingredients: [
      { name: "Schab wieprzowy mielony/chudy", amount: 700, unit: "g", category: "mieso" },
      { name: "Jajko", amount: 4, unit: "szt", category: "nabial" },
      { name: "Szpinak świeży", amount: 200, unit: "g", category: "warzywa" },
      { name: "Bułka tarta", amount: 4, unit: "łyżka", category: "zboza" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Sól, pieprz, majeranek", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Zmieszaj mielony schab z cebulą, bułką tartą, 1 jajkiem i przyprawami.",
      "Uformuj płaski placek mięsny, na środku ułóż szpinak i pozostałe (ugotowane na twardo lub surowe do zapieczenia) jajka, zwiń w rulon.",
      "Piecz w frytkownicy w formie/folii aluminiowej 25-30 minut w 180°C.",
      "Ziemniaki pokrój i upiecz obok, skropione oliwą i solą.",
      "Pokrój rulon w plastry, rozłóż do 4 pudełek z ziemniakami.",
    ],
  },
  {
    id: 27,
    name: "Klopsiki drobiowe w sosie koperkowym z ziemniakami",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 665,
    protein: 56,
    carbs: 63,
    fat: 19,
    weight_g: 700,
    ingredients: [
      { name: "Kurczak/indyk mielony", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Bułka tarta", amount: 3, unit: "łyżka", category: "zboza" },
      { name: "Jajko", amount: 1, unit: "szt", category: "nabial" },
      { name: "Jogurt naturalny 2%", amount: 200, unit: "g", category: "nabial" },
      { name: "Koperek świeży", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Bulion drobiowy", amount: 300, unit: "ml", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Ogórek", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wymieszaj mięso mielone z jajkiem, bułką tartą, solą i pieprzem, uformuj klopsiki.",
      "W garnku zeszklij cebulę na oliwie, dodaj bulion i klopsiki, gotuj pod przykryciem 15 minut.",
      "Dodaj jogurt i posiekany koperek, delikatnie wymieszaj (bez gotowania na dużym ogniu).",
      "Ugotuj ziemniaki w osobnym garnku.",
      "Pokrojonego ogórka wymieszaj z mix sałat i odrobiną oliwy na sałatkę.",
      "Rozłóż do 4 pudełek: ziemniaki, klopsiki w sosie koperkowym, sałatka.",
    ],
  },
  {
    id: 28,
    name: "Kurczak tikka masala z ryżem",
    protein_source: "Kurczak",
    equipment: ["thermomix", "garnek"],
    portions: 4,
    kcal: 745,
    protein: 57,
    carbs: 70,
    fat: 25,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Passata pomidorowa", amount: 300, unit: "g", category: "przyprawy_sosy" },
      { name: "Jogurt naturalny 2%", amount: 150, unit: "g", category: "nabial" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Szpinak świeży", amount: 300, unit: "g", category: "warzywa" },
      { name: "Imbir świeży", amount: 1, unit: "kawałek", category: "warzywa" },
      { name: "Przyprawa tikka masala/garam masala", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Masło klarowane/oliwa", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "W Thermomixie zblenduj cebulę, czosnek i imbir na pastę.",
      "Podsmaż pastę z przyprawami (kilka minut), dodaj pokrojonego kurczaka i obsmaż.",
      "Dodaj passatę i gotuj 15 minut, pod koniec wmieszaj szpinak, aż zwiędnie, i jogurt.",
      "Ugotuj ryż w garnku wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, kurczak tikka masala ze szpinakiem.",
    ],
  },
  {
    id: 29,
    name: "Wołowina po prowansalsku z kaszą gryczaną",
    protein_source: "Wołowina",
    equipment: ["garnek"],
    portions: 4,
    kcal: 697,
    protein: 49,
    carbs: 55,
    fat: 24,
    weight_g: 600,
    ingredients: [
      { name: "Wołowina chuda (udziec/łata)", amount: 700, unit: "g", category: "mieso" },
      { name: "Kasza gryczana", amount: 320, unit: "g", category: "zboza" },
      { name: "Pomidory krojone z puszki", amount: 400, unit: "g", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 3, unit: "ząbek", category: "warzywa" },
      { name: "Oliwki czarne", amount: 60, unit: "g", category: "przyprawy_sosy" },
      { name: "Zioła prowansalskie", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wołowinę pokrój w kostkę, obsmaż w garnku na oliwie.",
      "Dodaj cebulę i czosnek, chwilę podsmaż, dodaj pomidory, oliwki i zioła.",
      "Duś pod przykryciem 60-70 minut, aż mięso zmięknie.",
      "Ugotuj kaszę gryczaną wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: kasza, wołowina po prowansalsku.",
    ],
  },
  {
    id: 30,
    name: "Kurczak zapiekany z warzywami śródziemnomorskimi i ziemniakami",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 726,
    protein: 61,
    carbs: 55,
    fat: 28,
    weight_g: 650,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 600, unit: "g", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 200, unit: "g", category: "warzywa" },
      { name: "Ser feta light", amount: 120, unit: "g", category: "nabial" },
      { name: "Oliwki czarne", amount: 50, unit: "g", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Oregano suszone", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
    ],
    steps: [
      "Ziemniaki, cukinię i paprykę pokrój w kawałki, wymieszaj z oliwą, solą i oregano.",
      "Kurczaka natrzyj oliwą i przyprawami.",
      "Włóż warzywa do frytkownicy na 10 minut w 190°C, dołóż kurczaka i pomidorki, piecz kolejne 12-15 minut.",
      "Pokrusz na wierzch fetę i oliwki.",
      "Rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 31,
    name: "Indyk duszony w sosie curry z quinoa",
    protein_source: "Indyk",
    equipment: ["garnek"],
    portions: 4,
    kcal: 665,
    protein: 58,
    carbs: 60,
    fat: 19,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z indyka", amount: 600, unit: "g", category: "mieso" },
      { name: "Quinoa", amount: 280, unit: "g", category: "zboza" },
      { name: "Mleko kokosowe light", amount: 400, unit: "ml", category: "nabial" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Fasolka szparagowa", amount: 250, unit: "g", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Curry przyprawa", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Indyka pokrój w kostkę, cebulę i czosnek drobno, paprykę w paski.",
      "W garnku zeszklij cebulę z czosnkiem na oliwie, dodaj indyka i obsmaż.",
      "Dodaj paprykę, fasolkę szparagową, curry i mleko kokosowe, duś pod przykryciem 15-20 minut.",
      "Ugotuj quinoa wg instrukcji na opakowaniu (przepłucz przed gotowaniem).",
      "Rozłóż do 4 pudełek: quinoa, indyk w sosie curry.",
    ],
  },
  {
    id: 32,
    name: "Krupnik z kurczakiem i kaszą jęczmienną",
    protein_source: "Kurczak",
    equipment: ["thermomix"],
    portions: 4,
    kcal: 623,
    protein: 56,
    carbs: 60,
    fat: 16,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Kasza jęczmienna", amount: 240, unit: "g", category: "zboza" },
      { name: "Ziemniaki", amount: 200, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Pietruszka korzeń", amount: 100, unit: "g", category: "warzywa" },
      { name: "Seler korzeń", amount: 100, unit: "g", category: "warzywa" },
      { name: "Por", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Bulion drobiowy", amount: 800, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Lubczyk suszony, sól, pieprz", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Kurczaka ugotuj w bulionie do miękkości (ok. 20 minut), wyjmij i pokrój w kostkę.",
      "Warzywa pokrój w kostkę, dodaj do naczynia Thermomixa razem z bulionem i kaszą jęczmienną.",
      "Gotuj 25 minut/100°C na niskich obrotach (funkcja mieszania łopatką), aż kasza i warzywa zmiękną.",
      "Dodaj kurczaka, lubczyk i przyprawy, wymieszaj.",
      "Rozlej zupę do 4 pojemników.",
    ],
  },
  {
    id: 33,
    name: "Kurczak saté w sosie orzechowym z ryżem",
    protein_source: "Kurczak",
    equipment: ["garnek", "blender"],
    portions: 4,
    kcal: 760,
    protein: 60,
    carbs: 68,
    fat: 27,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Masło orzechowe", amount: 80, unit: "g", category: "przyprawy_sosy" },
      { name: "Sos sojowy", amount: 3, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Mleko kokosowe light", amount: 200, unit: "ml", category: "nabial" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Kapusta pekińska / mix sałat", amount: 250, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 100, unit: "g", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, cebulę, czosnek i paprykę drobno.",
      "W blenderze zmiksuj masło orzechowe, sos sojowy i mleko kokosowe na gładki sos.",
      "W garnku obsmaż kurczaka z cebulą i czosnkiem na oliwie, dodaj paprykę.",
      "Zalej sosem orzechowym, duś 10 minut, aż zgęstnieje.",
      "Kapustę pekińską poszatkuj, marchew zetrzyj — podaj jako chrupiący, surowy dodatek.",
      "Ugotuj ryż wg instrukcji na opakowaniu. Rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 34,
    name: "Indyk zapiekany w folii z ziemniakami i warzywami",
    protein_source: "Indyk",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 649,
    protein: 53,
    carbs: 60,
    fat: 18,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z indyka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Zioła prowansalskie", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
    ],
    steps: [
      "Indyka natrzyj oliwą, czosnkiem i ziołami.",
      "Warzywa pokrój w kawałki, wymieszaj z resztą oliwy i solą.",
      "Ułóż indyka i warzywa w folii aluminiowej lub naczyniu żaroodpornym pasującym do frytkownicy.",
      "Piecz 25 minut w 190°C, aż indyk osiągnie 75°C wewnątrz.",
      "Pokrój indyka w plastry, rozłóż do 4 pudełek z warzywami.",
    ],
  },
  {
    id: 35,
    name: "Wołowina stroganow z kaszą gryczaną",
    protein_source: "Wołowina",
    equipment: ["garnek"],
    portions: 4,
    kcal: 729,
    protein: 52,
    carbs: 60,
    fat: 26,
    weight_g: 600,
    ingredients: [
      { name: "Wołowina chuda (udziec/łata)", amount: 700, unit: "g", category: "mieso" },
      { name: "Kasza gryczana", amount: 320, unit: "g", category: "zboza" },
      { name: "Pieczarki", amount: 300, unit: "g", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Śmietana 12%", amount: 200, unit: "g", category: "nabial" },
      { name: "Musztarda", amount: 1, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Bulion wołowy/warzywny", amount: 200, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wołowinę pokrój w cienkie paski, obsmaż w garnku na oliwie.",
      "Dodaj cebulę i pieczarki (w plastrach), smaż do odparowania wody.",
      "Podlej bulionem, duś pod przykryciem 50-60 minut, aż mięso zmięknie.",
      "Dodaj śmietanę i musztardę, wymieszaj i podgrzej bez gotowania na dużym ogniu.",
      "Ugotuj kaszę gryczaną. Rozłóż do 4 pudełek: kasza, stroganow.",
    ],
  },
  {
    id: 36,
    name: "Kurczak marokański (tagine) z kuskusem",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 780,
    protein: 60,
    carbs: 78,
    fat: 23,
    weight_g: 720,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Kuskus", amount: 280, unit: "g", category: "zboza" },
      { name: "Suszone morele", amount: 160, unit: "g", category: "przyprawy_sosy" },
      { name: "Cieciorka z puszki", amount: 240, unit: "g", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Marchew", amount: 200, unit: "g", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Cynamon mielony", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Kumin mielony", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Bulion drobiowy/warzywny", amount: 300, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, cebulę, marchew i cukinię pokrój w kawałki.",
      "W garnku zeszklij cebulę i marchew na oliwie, dodaj kurczaka i obsmaż.",
      "Dodaj cukinię, przyprawy, morele, odsączoną cieciorkę i bulion, duś pod przykryciem 20-25 minut.",
      "Zalej kuskus wrzątkiem wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: kuskus, kurczak marokański z warzywami i cieciorką.",
    ],
  },
  {
    id: 37,
    name: "Schab w sosie pieczarkowym z kaszą jęczmienną",
    protein_source: "Schab",
    equipment: ["garnek"],
    portions: 4,
    kcal: 754,
    protein: 61,
    carbs: 60,
    fat: 24,
    weight_g: 600,
    ingredients: [
      { name: "Schab wieprzowy chudy", amount: 700, unit: "g", category: "mieso" },
      { name: "Kasza jęczmienna", amount: 320, unit: "g", category: "zboza" },
      { name: "Pieczarki", amount: 300, unit: "g", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Śmietana 12%", amount: 200, unit: "g", category: "nabial" },
      { name: "Bulion drobiowy/warzywny", amount: 200, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Schab pokrój w plastry, obsmaż w garnku na oliwie z obu stron, wyjmij.",
      "W tym samym garnku zeszklij cebulę i pieczarki (plastry), podlej bulionem.",
      "Wróć ze schabem do garnka, duś pod przykryciem 20 minut.",
      "Dodaj śmietanę, wymieszaj i podgrzej bez gotowania na dużym ogniu.",
      "Ugotuj kaszę jęczmienną. Rozłóż do 4 pudełek: kasza, schab w sosie.",
    ],
  },
  {
    id: 38,
    name: "Kurczak souvlaki z ryżem i sosem tzatziki",
    protein_source: "Kurczak",
    equipment: ["frytkownica", "blender"],
    portions: 4,
    kcal: 733,
    protein: 58,
    carbs: 65,
    fat: 24,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Jogurt naturalny 2%", amount: 400, unit: "g", category: "nabial" },
      { name: "Ogórek", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Pomidor", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Oregano suszone", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, wymieszaj z oliwą, oregano i solą, odstaw na 10 minut.",
      "Piecz w frytkownicy 15 minut w 190°C.",
      "W blenderze zmiksuj jogurt, starty ogórek i czosnek na sos tzatziki.",
      "Ugotuj ryż wg instrukcji na opakowaniu, pomidor i cebulę pokrój w kostkę.",
      "Rozłóż do 4 pudełek: ryż, kurczak, warzywa, sos tzatziki.",
    ],
  },
  {
    id: 39,
    name: "Indyk w sosie musztardowo-koperkowym z ziemniakami",
    protein_source: "Indyk",
    equipment: ["garnek"],
    portions: 4,
    kcal: 730,
    protein: 53,
    carbs: 63,
    fat: 25,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z indyka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Musztarda", amount: 2, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Śmietana 12%", amount: 200, unit: "g", category: "nabial" },
      { name: "Koperek świeży", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 200, unit: "g", category: "warzywa" },
      { name: "Bulion drobiowy/warzywny", amount: 200, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Indyka pokrój w kostkę, obsmaż w garnku na oliwie z cebulą.",
      "Podlej bulionem, duś pod przykryciem 15-18 minut.",
      "Dodaj musztardę, śmietanę i posiekany koperek, wymieszaj.",
      "Ugotuj ziemniaki w osobnym garnku.",
      "Przekrojone pomidorki wymieszaj z mix sałat i odrobiną oliwy na sałatkę.",
      "Rozłóż do 4 pudełek: ziemniaki, indyk w sosie, sałatka.",
    ],
  },
  {
    id: 40,
    name: "Kurczak katsu z ryżem i sosem curry",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 780,
    protein: 57,
    carbs: 78,
    fat: 23,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka (płaty)", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Bułka tarta", amount: 100, unit: "g", category: "zboza" },
      { name: "Mąka pszenna", amount: 40, unit: "g", category: "zboza" },
      { name: "Jajko", amount: 2, unit: "szt", category: "nabial" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Kapusta biała", amount: 300, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 100, unit: "g", category: "warzywa" },
      { name: "Jogurt naturalny 2%", amount: 80, unit: "g", category: "nabial" },
      { name: "Curry przyprawa", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Bulion drobiowy/warzywny", amount: 300, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek (spray/do natłuszczenia)", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Rozbite płaty kurczaka obtocz kolejno w mące, roztrzepanym jajku i bułce tartej.",
      "Skrop olejem, piecz w frytkownicy 12-15 minut w 190°C, obracając w połowie, aż będą chrupiące.",
      "W garnku zeszklij cebulę, dodaj curry i bulion, gotuj 10 minut na sos curry.",
      "Poszatkuj kapustę i marchew, wymieszaj z jogurtem na surówkę.",
      "Ugotuj ryż wg instrukcji na opakowaniu, kurczaka pokrój w paski.",
      "Rozłóż do 4 pudełek: ryż, kurczak katsu, surówka, sos curry osobno.",
    ],
  },
  {
    id: 41,
    name: "Wołowina teriyaki z ryżem i warzywami",
    protein_source: "Wołowina",
    equipment: ["garnek"],
    portions: 4,
    kcal: 751,
    protein: 46,
    carbs: 75,
    fat: 22,
    weight_g: 600,
    ingredients: [
      { name: "Wołowina chuda (udziec/łata)", amount: 700, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Brokuł", amount: 250, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 100, unit: "g", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Sos sojowy", amount: 4, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Miód", amount: 1, unit: "łyżka", category: "inne" },
      { name: "Olej sezamowy", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wołowinę pokrój w cienkie paski, obsmaż w garnku na oleju sezamowym.",
      "Dodaj warzywa pokrojone w słupki, smaż 5 minut.",
      "Wymieszaj sos sojowy z miodem, wlej do garnka, duś 8-10 minut, aż sos zgęstnieje.",
      "Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, wołowina teriyaki z warzywami.",
    ],
  },
  {
    id: 42,
    name: "Kurczak cacciatore z makaronem pełnoziarnistym",
    protein_source: "Kurczak",
    equipment: ["garnek"],
    portions: 4,
    kcal: 735,
    protein: 60,
    carbs: 65,
    fat: 24,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Makaron pełnoziarnisty", amount: 320, unit: "g", category: "zboza" },
      { name: "Passata pomidorowa", amount: 400, unit: "g", category: "przyprawy_sosy" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Oliwki czarne", amount: 60, unit: "g", category: "przyprawy_sosy" },
      { name: "Oregano suszone", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Kurczaka pokrój w kostkę, obsmaż w garnku na oliwie.",
      "Dodaj cebulę, czosnek i paprykę, chwilę podsmaż.",
      "Dodaj passatę, oliwki i oregano, duś pod przykryciem 20 minut.",
      "Ugotuj makaron pełnoziarnisty wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: makaron, kurczak cacciatore.",
    ],
  },
  {
    id: 43,
    name: "Schab pieczony w miodzie i musztardzie z kaszą bulgur",
    protein_source: "Schab",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 667,
    protein: 57,
    carbs: 60,
    fat: 20,
    weight_g: 550,
    ingredients: [
      { name: "Schab wieprzowy chudy", amount: 700, unit: "g", category: "mieso" },
      { name: "Bulgur", amount: 280, unit: "g", category: "zboza" },
      { name: "Miód", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Musztarda", amount: 2, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Jogurt naturalny 2%", amount: 100, unit: "g", category: "nabial" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wymieszaj miód z musztardą, natrzyj schab i odstaw na 10 minut.",
      "Piecz schab w frytkownicy 18-20 minut w 190°C, obracając w połowie.",
      "Ugotuj bulgur wg instrukcji na opakowaniu.",
      "Zetrzyj marchew, wymieszaj z jogurtem na surówkę.",
      "Schab pokrój w plastry, rozłóż do 4 pudełek z bulgurem i surówką.",
    ],
  },
  {
    id: 44,
    name: "Gyros z indyka w tortilli pełnoziarnistej",
    protein_source: "Indyk",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 750,
    protein: 60,
    carbs: 68,
    fat: 23,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z indyka", amount: 600, unit: "g", category: "mieso" },
      { name: "Tortilla pełnoziarnista", amount: 8, unit: "szt", category: "zboza" },
      { name: "Jogurt naturalny 2%", amount: 200, unit: "g", category: "nabial" },
      { name: "Ogórek", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Pomidor", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Cebula czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Sałata lodowa / mix sałat", amount: 250, unit: "g", category: "warzywa" },
      { name: "Przyprawa gyros/oregano", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Indyka pokrój w paski, wymieszaj z przyprawą gyros i oliwą, odstaw na 10 minut.",
      "Piecz w frytkownicy 12-15 minut w 190°C.",
      "Pomidor, ogórek i cebulę pokrój w kostkę, wymieszaj jogurt na sos.",
      "Podgrzej tortille.",
      "Rozłóż do 4 pudełek: indyk, warzywa, spora garść sałaty, sos, tortille osobno — zawijaj z dużą ilością sałaty tuż przed jedzeniem.",
    ],
  },
  {
    id: 45,
    name: "Kurczak w czerwonym curry (tajskim) z ryżem",
    protein_source: "Kurczak",
    equipment: ["garnek", "thermomix"],
    portions: 4,
    kcal: 715,
    protein: 56,
    carbs: 65,
    fat: 24,
    weight_g: 600,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Mleko kokosowe light", amount: 800, unit: "ml", category: "nabial" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Fasolka szparagowa", amount: 150, unit: "g", category: "warzywa" },
      { name: "Czerwona pasta curry", amount: 3, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Bazylia świeża", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "W Thermomixie lub garnku podsmaż pastę curry na oliwie (kilka minut).",
      "Dodaj pokrojonego kurczaka i obsmaż, następnie mleko kokosowe.",
      "Dodaj paprykę i fasolkę, duś 15-20 minut.",
      "Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, curry, świeża bazylia na wierzch.",
    ],
  },
  {
    id: 46,
    name: "Klopsiki wołowe w sosie pomidorowo-paprykowym z ryżem",
    protein_source: "Wołowina",
    equipment: ["garnek"],
    portions: 4,
    kcal: 755,
    protein: 41,
    carbs: 78,
    fat: 23,
    weight_g: 700,
    ingredients: [
      { name: "Wołowina mielona chuda", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Bułka tarta", amount: 3, unit: "łyżka", category: "zboza" },
      { name: "Jajko", amount: 1, unit: "szt", category: "nabial" },
      { name: "Passata pomidorowa", amount: 400, unit: "g", category: "przyprawy_sosy" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Ogórek", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wymieszaj mieloną wołowinę z jajkiem, bułką tartą, solą i pieprzem, uformuj klopsiki.",
      "Obsmaż klopsiki w garnku na oliwie z każdej strony.",
      "Dodaj cebulę i paprykę, chwilę podsmaż, zalej passatą.",
      "Duś pod przykryciem 20 minut. Ugotuj ryż wg instrukcji na opakowaniu.",
      "Pokrojonego ogórka wymieszaj z mix sałat i odrobiną oliwy na sałatkę.",
      "Rozłóż do 4 pudełek: ryż, klopsiki w sosie, sałatka.",
    ],
  },
  {
    id: 47,
    name: "Kurczak faszerowany suszonymi pomidorami i fetą z ziemniakami",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 730,
    protein: 63,
    carbs: 58,
    fat: 25,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka (do faszerowania)", amount: 600, unit: "g", category: "mieso" },
      { name: "Suszone pomidory w oliwie", amount: 80, unit: "g", category: "przyprawy_sosy" },
      { name: "Ser feta light", amount: 160, unit: "g", category: "nabial" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 200, unit: "g", category: "warzywa" },
      { name: "Ogórek", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
      { name: "Bazylia suszona", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
    ],
    steps: [
      "Natnij pierś kurczaka wzdłuż, tworząc kieszonkę, napełnij pokrojonymi suszonymi pomidorami i fetą.",
      "Spinaj wykałaczką, natrzyj oliwą, czosnkiem i bazylią.",
      "Ziemniaki pokrój w ćwiartki, wymieszaj z resztą oliwy i solą.",
      "Piecz kurczaka i ziemniaki w frytkownicy 20 minut w 190°C.",
      "Pomidorki i ogórka pokrój, wymieszaj z mix sałat i odrobiną oliwy na sałatkę śródziemnomorską.",
      "Rozłóż do 4 pudełek: kurczak faszerowany, ziemniaki, sałatka.",
    ],
  },
  {
    id: 48,
    name: "Gulasz ze schabu (paprykarz) z kaszą jęczmienną",
    protein_source: "Schab",
    equipment: ["garnek"],
    portions: 4,
    kcal: 735,
    protein: 59,
    carbs: 65,
    fat: 23,
    weight_g: 700,
    ingredients: [
      { name: "Schab wieprzowy chudy", amount: 700, unit: "g", category: "mieso" },
      { name: "Kasza jęczmienna", amount: 320, unit: "g", category: "zboza" },
      { name: "Papryka czerwona", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Koncentrat pomidorowy", amount: 2, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Papryka słodka mielona", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Bulion drobiowy/warzywny", amount: 300, unit: "ml", category: "przyprawy_sosy" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Ogórek", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Schab pokrój w kostkę, obsmaż w garnku na oliwie.",
      "Dodaj cebulę i paprykę, chwilę podsmaż, dodaj koncentrat i paprykę mieloną.",
      "Zalej bulionem, duś pod przykryciem 25-30 minut.",
      "Ugotuj kaszę jęczmienną wg instrukcji na opakowaniu.",
      "Pokrojonego ogórka wymieszaj z mix sałat i odrobiną oliwy na sałatkę.",
      "Rozłóż do 4 pudełek: kasza, gulasz ze schabu, sałatka.",
    ],
  },
  {
    id: 49,
    name: "Pieczony indyk w ziołach prowansalskich z warzywami śródziemnomorskimi",
    protein_source: "Indyk",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 649,
    protein: 53,
    carbs: 50,
    fat: 22,
    weight_g: 650,
    ingredients: [
      { name: "Pierś z indyka", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 600, unit: "g", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 200, unit: "g", category: "warzywa" },
      { name: "Oliwki czarne", amount: 50, unit: "g", category: "przyprawy_sosy" },
      { name: "Zioła prowansalskie", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Indyka natrzyj oliwą i ziołami prowansalskimi.",
      "Ziemniaki i cukinię pokrój w kawałki, wymieszaj z resztą oliwy i solą.",
      "Włóż warzywa do frytkownicy na 10 minut w 190°C, dołóż indyka, paprykę i pomidorki.",
      "Piecz razem kolejne 15 minut, aż indyk osiągnie 75°C wewnątrz.",
      "Posyp oliwkami, rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 50,
    name: "Wołowina duszona w sosie BBQ z ziemniakami",
    protein_source: "Wołowina",
    equipment: ["garnek"],
    portions: 4,
    kcal: 660,
    protein: 45,
    carbs: 58,
    fat: 21,
    weight_g: 700,
    ingredients: [
      { name: "Wołowina chuda (udziec/łata)", amount: 700, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Keczup", amount: 3, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Miód", amount: 1, unit: "łyżka", category: "inne" },
      { name: "Papryka wędzona mielona", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Kapusta biała", amount: 300, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 100, unit: "g", category: "warzywa" },
      { name: "Jogurt naturalny 2%", amount: 80, unit: "g", category: "nabial" },
      { name: "Bulion wołowy/warzywny", amount: 300, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wołowinę pokrój w kostkę, obsmaż w garnku na oliwie z cebulą.",
      "Dodaj keczup, miód, wędzoną paprykę i bulion.",
      "Duś pod przykryciem 60-70 minut, aż mięso zmięknie i sos zgęstnieje.",
      "Ugotuj ziemniaki w osobnym garnku.",
      "Poszatkuj kapustę i marchew, wymieszaj z jogurtem na surówkę coleslaw.",
      "Rozłóż do 4 pudełek: ziemniaki, wołowina w sosie BBQ, surówka.",
    ],
  },
  {
    id: 51,
    name: "Wołowina po burgundzku z puree ziemniaczanym",
    protein_source: "Wołowina",
    equipment: ["garnek", "thermomix"],
    portions: 4,
    kcal: 694,
    protein: 47,
    carbs: 60,
    fat: 22,
    weight_g: 650,
    ingredients: [
      { name: "Wołowina chuda (udziec/łata)", amount: 700, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Pieczarki", amount: 200, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Koncentrat pomidorowy", amount: 1, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Mleko 1,5%", amount: 150, unit: "ml", category: "nabial" },
      { name: "Masło", amount: 20, unit: "g", category: "nabial" },
      { name: "Bulion wołowy/warzywny", amount: 400, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wołowinę pokrój w kostkę, obsmaż w garnku na oliwie.",
      "Dodaj cebulę, marchew i pieczarki, chwilę podsmaż, dodaj koncentrat i bulion.",
      "Duś pod przykryciem 60-70 minut, aż mięso zmięknie.",
      "Ziemniaki ugotuj i zblenduj w Thermomixie z mlekiem i masłem na puree.",
      "Rozłóż do 4 pudełek: puree, wołowina po burgundzku.",
    ],
  },
  {
    id: 52,
    name: "Kurczak saltimbocca z szynką i szałwią, ziemniaki",
    protein_source: "Kurczak",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 655,
    protein: 58,
    carbs: 53,
    fat: 21,
    weight_g: 700,
    ingredients: [
      { name: "Pierś z kurczaka (płaty)", amount: 600, unit: "g", category: "mieso" },
      { name: "Szynka dojrzewająca (parmeńska/podobna)", amount: 80, unit: "g", category: "mieso" },
      { name: "Szałwia świeża", amount: 8, unit: "listek", category: "warzywa" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Mix sałat", amount: 150, unit: "g", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 200, unit: "g", category: "warzywa" },
      { name: "Ocet balsamiczny", amount: 1, unit: "łyżka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
      { name: "Sól, pieprz", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Na każdym płacie kurczaka ułóż listek szałwii i plaster szynki, spinaj wykałaczką.",
      "Ziemniaki pokrój w ćwiartki, wymieszaj z oliwą i solą.",
      "Piecz kurczaka (szynką do góry) i ziemniaki w frytkownicy 15-18 minut w 190°C.",
      "Sprawdź, czy kurczak jest dobrze wypieczony.",
      "Przekrojone pomidorki wymieszaj z mix sałat, oliwą i octem balsamicznym na sałatkę.",
      "Rozłóż do 4 pudełek: kurczak saltimbocca, ziemniaki, sałatka.",
    ],
  },
  {
    id: 53,
    name: "Klopsiki z indyka w sosie curry z ryżem",
    protein_source: "Indyk",
    equipment: ["garnek"],
    portions: 4,
    kcal: 740,
    protein: 53,
    carbs: 72,
    fat: 23,
    weight_g: 700,
    ingredients: [
      { name: "Indyk mielony", amount: 600, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Bułka tarta", amount: 3, unit: "łyżka", category: "zboza" },
      { name: "Jajko", amount: 1, unit: "szt", category: "nabial" },
      { name: "Mleko kokosowe light", amount: 200, unit: "ml", category: "nabial" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Groszek zielony mrożony", amount: 200, unit: "g", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Curry przyprawa", amount: 2, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Wymieszaj mielonego indyka z jajkiem, bułką tartą, solą i pieprzem, uformuj klopsiki.",
      "Obsmaż klopsiki w garnku na oliwie z każdej strony.",
      "Dodaj cebulę, paprykę, curry i mleko kokosowe, duś pod przykryciem 12 minut.",
      "Dodaj groszek, gotuj jeszcze 3-4 minuty.",
      "Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, klopsiki w sosie curry z groszkiem.",
    ],
  },
  {
    id: 54,
    name: "Zrazy wołowe zawijane z boczkiem i ogórkiem kiszonym, kasza gryczana",
    protein_source: "Wołowina",
    equipment: ["garnek"],
    portions: 4,
    kcal: 689,
    protein: 53,
    carbs: 55,
    fat: 24,
    weight_g: 600,
    ingredients: [
      { name: "Wołowina chuda (cienkie płaty na zrazy)", amount: 700, unit: "g", category: "mieso" },
      { name: "Boczek wędzony", amount: 80, unit: "g", category: "mieso" },
      { name: "Ogórek kiszony", amount: 3, unit: "szt", category: "warzywa" },
      { name: "Cebula", amount: 2, unit: "szt", category: "warzywa" },
      { name: "Kasza gryczana", amount: 320, unit: "g", category: "zboza" },
      { name: "Śmietana 12%", amount: 100, unit: "g", category: "nabial" },
      { name: "Mąka pszenna", amount: 1, unit: "łyżka", category: "zboza" },
      { name: "Bulion wołowy/warzywny", amount: 300, unit: "ml", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Na każdym płacie wołowiny ułóż plasterek boczku, cebulę i ćwiartkę ogórka, zwiń i spinaj wykałaczką.",
      "Obsmaż zrazy w garnku na oliwie z każdej strony.",
      "Podlej bulionem, duś pod przykryciem 60-70 minut, aż mięso zmięknie.",
      "Zagęść sos mąką wymieszaną ze śmietaną, gotuj jeszcze 5 minut.",
      "Ugotuj kaszę gryczaną. Rozłóż do 4 pudełek: kasza, zrazy w sosie.",
    ],
  },
  {
    id: 55,
    name: "Dorsz pieczony w folii z warzywami i ziemniakami",
    protein_source: "Ryba",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 600,
    protein: 45,
    carbs: 55,
    fat: 16,
    weight_g: 600,
    ingredients: [
      { name: "Filet z dorsza", amount: 800, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Cytryna", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Koperek świeży", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
      { name: "Sól, pieprz", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Ziemniaki, marchew i cukinię pokrój w kawałki, wymieszaj z oliwą i solą.",
      "Włóż warzywa do frytkownicy na 12 minut w 190°C.",
      "Filety z dorsza skrop cytryną, oliwą, posyp koperkiem i solą.",
      "Dołóż rybę do warzyw, piecz kolejne 8-10 minut, aż ryba będzie się rozpadać pod widelcem.",
      "Rozłóż do 4 pudełek: ziemniaki, warzywa, dorsz.",
    ],
  },
  {
    id: 56,
    name: "Łosoś pieczony z brokułem i puree ziemniaczanym",
    protein_source: "Ryba",
    equipment: ["frytkownica", "thermomix"],
    portions: 4,
    kcal: 686,
    protein: 40,
    carbs: 50,
    fat: 30,
    weight_g: 600,
    ingredients: [
      { name: "Filet z łososia", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 700, unit: "g", category: "warzywa" },
      { name: "Brokuł", amount: 400, unit: "g", category: "warzywa" },
      { name: "Mleko 1,5%", amount: 150, unit: "ml", category: "nabial" },
      { name: "Masło", amount: 20, unit: "g", category: "nabial" },
      { name: "Cytryna", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Koperek świeży", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Łososia skrop cytryną, oliwą, posyp koperkiem i solą.",
      "Piecz w frytkownicy 12-15 minut w 180°C, aż będzie się łatwo rozdzielać widelcem.",
      "Ziemniaki ugotuj i zblenduj w Thermomixie z mlekiem i masłem na puree.",
      "Brokuł ugotuj na parze/w wodzie do miękkości.",
      "Rozłóż do 4 pudełek: puree, brokuł, łosoś.",
    ],
  },
  {
    id: 57,
    name: "Pstrąg pieczony z płatkami migdałów i warzywami korzeniowymi",
    protein_source: "Ryba",
    equipment: ["frytkownica"],
    portions: 4,
    kcal: 644,
    protein: 49,
    carbs: 55,
    fat: 22,
    weight_g: 600,
    ingredients: [
      { name: "Filet z pstrąga", amount: 800, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 400, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 200, unit: "g", category: "warzywa" },
      { name: "Pietruszka korzeń", amount: 150, unit: "g", category: "warzywa" },
      { name: "Płatki migdałowe", amount: 60, unit: "g", category: "przyprawy_sosy" },
      { name: "Cytryna", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Masło", amount: 20, unit: "g", category: "nabial" },
      { name: "Oliwa z oliwek", amount: 1, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Ziemniaki, marchew i pietruszkę pokrój w słupki, wymieszaj z oliwą i solą.",
      "Włóż warzywa do frytkownicy na 12 minut w 190°C.",
      "Filety z pstrąga skrop cytryną, dołóż do warzyw, piecz 8-10 minut.",
      "Na patelni/w rondelku zrumień płatki migdałów na maśle (2 minuty) i polej rybę.",
      "Rozłóż do 4 pudełek: warzywa, pstrąg z migdałami.",
    ],
  },
  {
    id: 58,
    name: "Mintaj duszony w sosie pomidorowym z ryżem",
    protein_source: "Ryba",
    equipment: ["garnek"],
    portions: 4,
    kcal: 660,
    protein: 44,
    carbs: 71,
    fat: 17,
    weight_g: 700,
    ingredients: [
      { name: "Filet z mintaja", amount: 800, unit: "g", category: "mieso" },
      { name: "Ryż biały", amount: 320, unit: "g", category: "zboza" },
      { name: "Passata pomidorowa", amount: 400, unit: "g", category: "przyprawy_sosy" },
      { name: "Cebula", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Papryka czerwona", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Bazylia suszona", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "W garnku zeszklij cebulę, czosnek i paprykę na oliwie.",
      "Cukinię pokrój w kostkę, dodaj do garnka razem z passatą i bazylią, gotuj 10 minut.",
      "Dodaj filety z mintaja, duś pod przykryciem 8-10 minut, aż ryba będzie ugotowana (nie mieszaj zbyt mocno, żeby się nie rozpadła).",
      "Ugotuj ryż wg instrukcji na opakowaniu.",
      "Rozłóż do 4 pudełek: ryż, mintaj w sosie pomidorowym z cukinią.",
    ],
  },
  {
    id: 59,
    name: "Krem rybny z łososia i warzyw",
    protein_source: "Ryba",
    equipment: ["thermomix"],
    portions: 4,
    kcal: 760,
    protein: 37,
    carbs: 45,
    fat: 42,
    weight_g: 600,
    ingredients: [
      { name: "Filet z łososia", amount: 600, unit: "g", category: "mieso" },
      { name: "Ziemniaki", amount: 400, unit: "g", category: "warzywa" },
      { name: "Marchew", amount: 150, unit: "g", category: "warzywa" },
      { name: "Por", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Seler korzeń", amount: 100, unit: "g", category: "warzywa" },
      { name: "Śmietana 12%", amount: 200, unit: "g", category: "nabial" },
      { name: "Bulion warzywny", amount: 400, unit: "ml", category: "przyprawy_sosy" },
      { name: "Koperek świeży", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Warzywa (ziemniaki, marchew, por, seler) umieść w naczyniu Thermomixa z bulionem, gotuj 20 minut/100°C.",
      "Zblenduj na gładki krem, dodaj śmietanę.",
      "Łososia pokrój w kostkę, dodaj do kremu i gotuj jeszcze 8-10 minut/90°C (funkcja odwrotnych obrotów), aż ryba się ugotuje.",
      "Dopraw solą, pieprzem i koperkiem.",
      "Rozlej krem rybny do 4 pojemników.",
    ],
  },
  {
    id: 60,
    name: "Makaron pełnoziarnisty z kurczakiem w domowym pesto bazyliowym",
    protein_source: "Kurczak",
    equipment: ["garnek", "blender"],
    portions: 4,
    kcal: 800,
    protein: 62,
    carbs: 75,
    fat: 28,
    weight_g: 750,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Makaron pełnoziarnisty", amount: 320, unit: "g", category: "zboza" },
      { name: "Bazylia świeża", amount: 2, unit: "pęczek", category: "warzywa" },
      { name: "Orzechy włoskie lub pestki słonecznika", amount: 60, unit: "g", category: "przyprawy_sosy" },
      { name: "Parmezan / ser typu grana, starty", amount: 40, unit: "g", category: "nabial" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Rukola", amount: 100, unit: "g", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 300, unit: "g", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 4, unit: "łyżka", category: "inne" },
      { name: "Sól, pieprz", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "W blenderze zmiksuj bazylię, orzechy/pestki, parmezan, czosnek i oliwę na gładkie pesto (dodaj odrobinę wody z makaronu, jeśli za gęste).",
      "Kurczaka pokrój w kostkę, podduś w garnku na odrobinie oliwy do miękkości.",
      "Cukinię pokrój w półplasterki, podduś kilka minut razem z kurczakiem.",
      "Ugotuj makaron pełnoziarnisty wg instrukcji na opakowaniu.",
      "Wymieszaj gorący makaron z pesto, kurczakiem i cukinią, na koniec wmieszaj rukolę i przekrojone pomidorki (dodają dużo objętości przy niewielkiej liczbie kalorii).",
      "Rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 61,
    name: "Makaron z indykiem w sosie z pieczonej papryki i pomidorów (czerwone pesto)",
    protein_source: "Indyk",
    equipment: ["frytkownica", "blender", "garnek"],
    portions: 4,
    kcal: 720,
    protein: 58,
    carbs: 72,
    fat: 22,
    weight_g: 750,
    ingredients: [
      { name: "Pierś z indyka", amount: 600, unit: "g", category: "mieso" },
      { name: "Makaron pełnoziarnisty", amount: 320, unit: "g", category: "zboza" },
      { name: "Papryka czerwona", amount: 3, unit: "szt", category: "warzywa" },
      { name: "Pomidory suszone w oliwie", amount: 60, unit: "g", category: "przyprawy_sosy" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Migdały lub orzechy nerkowca", amount: 40, unit: "g", category: "przyprawy_sosy" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Rukola", amount: 100, unit: "g", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
      { name: "Bazylia suszona", amount: 1, unit: "łyżeczka", category: "przyprawy_sosy" },
    ],
    steps: [
      "Paprykę piecz w całości w frytkownicy 15-18 minut w 200°C, aż skórka się przyciemni, obierz ze skórki.",
      "W blenderze zmiksuj upieczoną paprykę, suszone pomidory, czosnek, migdały i oliwę na gładki sos.",
      "Indyka pokrój w paski, podduś w garnku na oliwie z cukinią pokrojoną w kostkę.",
      "Ugotuj makaron wg instrukcji na opakowaniu.",
      "Wymieszaj makaron z sosem, indykiem i cukinią, na koniec wmieszaj rukolę.",
      "Rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 62,
    name: "Makaron pełnoziarnisty z kurczakiem w sosie szpinakowo-ziołowym",
    protein_source: "Kurczak",
    equipment: ["garnek", "blender"],
    portions: 4,
    kcal: 730,
    protein: 63,
    carbs: 70,
    fat: 22,
    weight_g: 780,
    ingredients: [
      { name: "Pierś z kurczaka", amount: 600, unit: "g", category: "mieso" },
      { name: "Makaron pełnoziarnisty", amount: 320, unit: "g", category: "zboza" },
      { name: "Szpinak świeży", amount: 400, unit: "g", category: "warzywa" },
      { name: "Natka pietruszki", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Orzechy nerkowca lub pestki słonecznika", amount: 40, unit: "g", category: "przyprawy_sosy" },
      { name: "Jogurt naturalny 2%", amount: 150, unit: "g", category: "nabial" },
      { name: "Pomidorki koktajlowe", amount: 250, unit: "g", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
      { name: "Sól, pieprz", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "Połowę szpinaku (surowego) zblenduj z natką pietruszki, czosnkiem, orzechami, jogurtem i oliwą na gładki zielony sos.",
      "Kurczaka pokrój w kostkę, podduś w garnku na oliwie do miękkości.",
      "Resztę szpinaku podduś krótko w tym samym garnku, aż zwiędnie.",
      "Ugotuj makaron wg instrukcji na opakowaniu.",
      "Wymieszaj gorący makaron z sosem (poza ogniem, żeby jogurt się nie zważył), kurczakiem, duszonym szpinakiem i przekrojonymi pomidorkami.",
      "Rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 63,
    name: "Makaron z wołowiną w sosie z zielonego groszku, mięty i bazylii",
    protein_source: "Wołowina",
    equipment: ["garnek", "blender"],
    portions: 4,
    kcal: 745,
    protein: 50,
    carbs: 72,
    fat: 26,
    weight_g: 750,
    ingredients: [
      { name: "Wołowina chuda (udziec/łata, cienkie paski)", amount: 600, unit: "g", category: "mieso" },
      { name: "Makaron pełnoziarnisty", amount: 320, unit: "g", category: "zboza" },
      { name: "Groszek zielony mrożony", amount: 350, unit: "g", category: "warzywa" },
      { name: "Mięta świeża", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Bazylia świeża", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Parmezan / ser typu grana, starty", amount: 30, unit: "g", category: "nabial" },
      { name: "Czosnek", amount: 1, unit: "ząbek", category: "warzywa" },
      { name: "Cukinia", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 3, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "Ugotuj 250g groszku 3 minuty w osolonej wodzie, odcedź, zblenduj z miętą, bazylią, parmezanem, czosnkiem i oliwą na gładki sos.",
      "Wołowinę obsmaż w garnku na oliwie, dodaj cukinię pokrojoną w kostkę i pozostały groszek, podduś 5 minut.",
      "Ugotuj makaron wg instrukcji na opakowaniu.",
      "Wymieszaj makaron z sosem, wołowiną, cukinią i groszkiem.",
      "Rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 64,
    name: "Makaron ze schabem w sosie z suszonych pomidorów, oliwek i rukoli (pesto rosso)",
    protein_source: "Schab",
    equipment: ["garnek", "blender"],
    portions: 4,
    kcal: 735,
    protein: 60,
    carbs: 68,
    fat: 26,
    weight_g: 750,
    ingredients: [
      { name: "Schab wieprzowy chudy", amount: 600, unit: "g", category: "mieso" },
      { name: "Makaron pełnoziarnisty", amount: 320, unit: "g", category: "zboza" },
      { name: "Pomidory suszone w oliwie", amount: 100, unit: "g", category: "przyprawy_sosy" },
      { name: "Oliwki czarne", amount: 60, unit: "g", category: "przyprawy_sosy" },
      { name: "Migdały lub orzechy nerkowca", amount: 40, unit: "g", category: "przyprawy_sosy" },
      { name: "Czosnek", amount: 2, unit: "ząbek", category: "warzywa" },
      { name: "Rukola", amount: 150, unit: "g", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 250, unit: "g", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 2, unit: "łyżka", category: "inne" },
    ],
    steps: [
      "W blenderze zmiksuj suszone pomidory, połowę oliwek, migdały, czosnek i oliwę na gęsty sos (pesto rosso).",
      "Schab pokrój w paski, obsmaż w garnku na oliwie do miękkości.",
      "Ugotuj makaron wg instrukcji na opakowaniu.",
      "Wymieszaj makaron z sosem i schabem, na koniec wmieszaj rukolę, przekrojone pomidorki i resztę oliwek.",
      "Rozłóż do 4 pudełek.",
    ],
  },
  {
    id: 65,
    name: "Makaron pełnoziarnisty z tuńczykiem, pomidorkami i sosem ziołowo-czosnkowym",
    protein_source: "Ryba",
    equipment: ["garnek", "blender"],
    portions: 4,
    kcal: 690,
    protein: 52,
    carbs: 75,
    fat: 20,
    weight_g: 750,
    ingredients: [
      { name: "Tuńczyk w wodzie z puszki (odsączony)", amount: 480, unit: "g", category: "mieso" },
      { name: "Makaron pełnoziarnisty", amount: 320, unit: "g", category: "zboza" },
      { name: "Natka pietruszki", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Bazylia świeża", amount: 1, unit: "pęczek", category: "warzywa" },
      { name: "Czosnek", amount: 3, unit: "ząbek", category: "warzywa" },
      { name: "Cytryna", amount: 1, unit: "szt", category: "warzywa" },
      { name: "Pomidorki koktajlowe", amount: 350, unit: "g", category: "warzywa" },
      { name: "Rukola", amount: 100, unit: "g", category: "warzywa" },
      { name: "Oliwa z oliwek", amount: 4, unit: "łyżka", category: "inne" },
      { name: "Sól, pieprz, chili (opcjonalnie)", amount: 1, unit: "szczypta", category: "przyprawy_sosy" },
    ],
    steps: [
      "W blenderze zmiksuj natkę pietruszki, bazylię, czosnek, sok z cytryny i oliwę na sos ziołowo-czosnkowy.",
      "Przekrój pomidorki koktajlowe na połówki.",
      "Ugotuj makaron wg instrukcji na opakowaniu.",
      "Wymieszaj gorący makaron z sosem, odsączonym tuńczykiem (rozdrobnionym widelcem) i pomidorkami — nie podgrzewaj tuńczyka na dużym ogniu, wystarczy ciepło makaronu.",
      "Na koniec wmieszaj rukolę.",
      "Rozłóż do 4 pudełek. To najszybszy przepis w bazie — świetny na dzień, gdy brakuje czasu.",
    ],
  },
];
